Possible errors :<br>
In api/main.py you can see <br>![image](https://github.com/user-attachments/assets/0e5cd33b-f0b8-4c37-be8c-01ffac380bdd)<br>
change the allow_origins to the port in which your fornt is running (eg: allow_origins=['http://localhost:your_port'] )

